language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: s3
  skip_cleanup: true
  bucket: peetg-react-rls
  region: af-south-1
  project: ./build/
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
on:
  branch: master
